inputs_def:
  - handle: text
    json_schema:
      type: string
      ui:widget: text
  - handle: text_kind
    json_schema:
      enum:
        - text
        - ssml
      ui:options:
        labels:
          - Text
          - SSML
    value: text
  - handle: region
    json_schema:
      type: string
  - handle: key
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: output_path
    json_schema:
      type: string
      ui:widget: file
  - handle: voice
    json_schema:
      type: string
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Speech
