inputs_def:
  - handle: text
    json_schema:
      type: string
      ui:widget: text
  - handle: text_kind
    json_schema:
      enum:
        - text
        - ssml
      ui:options:
        labels:
          - Text
          - SSML
    value: text
  - handle: region
    json_schema:
      enum:
        - eastasia
        - southeastasia
        - australiaeast
        - northeurope
        - westeurope
        - eastus
        - eastus2
        - southcentralus
        - westcentralus
        - westus
        - westus2
        - brazilsouth
      ui:options:
        labels:
          - East Asia
          - Southeast Asia
          - Australia east
          - North Europe
          - West Europe
          - East US
          - East US 2
          - South central US
          - West central US
          - west US
          - West US 2
          - Brazil south
    value: eastasia
  - handle: key
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: voice
    json_schema:
      type: string
  - handle: granularity
    json_schema:
      enum:
        - none
        - sentence
        - word
      ui:options:
        labels:
          - None
          - Sentence
          - Word
    value: none
  - handle: output_path
    json_schema:
      type: string
      ui:widget: file
    nullable: true
outputs_def:
  - handle: output_path
    json_schema:
      type: string
      ui:widget: file
  - handle: sentences
    json_schema:
      type: array
      items:
        type: string
    nullable: false
ui:
  default_width: 413.3075034797966
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Speech
